 syntax on
 set t_db=
 set number
 set norelativenumber
 set cursorline
 set wrap
 set showcmd
 set wildmenu

 set hlsearch
 exec "nohlsearch"
 set incsearch
 set ignorecase
 set smartcase

 noremap n h
 noremap u k
 noremap i l
 noremap e j

 map s <nop>
 map S :w<CR>
 map Q :q<CR>
 map R :source d:/GIT/Git/etc/vimrc<CR>
